import React from "react";
import CategoryPage from "../Components/MainComponents/CategoryPage";
import { Mukta } from "next/font/google";

// Importing Mukta font from Google Fonts
const mukta = Mukta({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["devanagari", "latin"], // You can choose subsets based on your needs
  variable: "--font-mukta",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function page() {
  return (
    <div className={`${mukta.className} antialiased`}>
      <CategoryPage />
    </div>
  );
}
